package routers

import (
	beego "github.com/beego/beego/v2/server/web"
	"iotServer/controllers"
	"iotServer/controllers/edgeController"
)

func init() {
	ns := beego.NewNamespace("/api",
		beego.NSNamespace("/user",
			beego.NSInclude(
				&controllers.UserController{},
			),
		),
		beego.NSNamespace("/role",
			beego.NSInclude(
				&controllers.RoleController{},
			),
		),
		beego.NSNamespace("/menu",
			beego.NSInclude(
				&controllers.MenuController{},
			),
		),
		beego.NSNamespace("/scada",
			beego.NSInclude(
				&edgeController.HistoryController{},
				&edgeController.RealController{},
				&edgeController.TagController{},
				&controllers.AlertController{},
			),
		),
		beego.NSNamespace("/ws",
			beego.NSInclude(
				&edgeController.WebsocketController{},
			),
		),
		beego.NSNamespace("/product",
			beego.NSInclude(
				&controllers.ProductController{},
			),
		),
		beego.NSNamespace("/model",
			beego.NSInclude(
				&controllers.ModelController{},
			),
		),
		beego.NSNamespace("/write",
			beego.NSInclude(
				&controllers.WriteController{},
			),
		),
		beego.NSNamespace("/label",
			beego.NSInclude(
				&edgeController.LabelController{},
			),
		),
		beego.NSNamespace("/",
			beego.NSInclude(
				&edgeController.MainController{},
			),
		),
		beego.NSNamespace("/ekuiper",
			beego.NSInclude(
				&controllers.EkuiperController{},
			),
		),
		beego.NSNamespace("/rule",
			beego.NSInclude(
				&controllers.RuleController{},
			),
		),
		beego.NSNamespace("/device",
			beego.NSInclude(
				&controllers.DeviceController{},
			),
		),
		beego.NSNamespace("/scene",
			beego.NSInclude(
				&controllers.SceneController{},
			),
		),
		beego.NSNamespace("/engine",
			beego.NSInclude(
				&controllers.EngineController{},
			),
		),
		beego.NSNamespace("/udf",
			beego.NSInclude(
				&controllers.UdfController{},
			),
		),
		beego.NSNamespace("/report",
			beego.NSInclude(
				&controllers.ReportController{},
			),
		),
		beego.NSNamespace("/position",
			beego.NSInclude(
				&controllers.PositionController{},
			),
		),

		beego.NSNamespace("/group",
			beego.NSInclude(
				&controllers.GroupController{},
			),
		),
		beego.NSNamespace("/project",
			beego.NSInclude(
				&controllers.ProjectController{},
			),
		),
	)
	beego.AddNamespace(ns)
}
